version: "3.9"

services:
  torrentbot:
    build: .
    container_name: torrentbot
    restart: unless-stopped
    volumes:
      - ./data/downloads:/app/data/downloads
    ports:
      - "8080:8080" 
    environment:
      - TZ=Africa/Kinshasa
    command: python3.9 main.py
